= Taint と Toleration
:navtitle: app-basics
include::_attributes.adoc[]

本コンテンツは、link:https://github.com/team-ohc-jp-place/openshift-cns-testdrive[MAD Workshop Ops Track] の内容を利用しています。

== 演習の概要
以前の演習では、インフラノードを作成し、 https://docs.openshift.com/container-platform/4.3/nodes/scheduling/nodes-scheduler-node-selectors.html[nodeSelector] を使用して、ワークロードを配置する場所を制御しました。
あるタスクを実行するために、どのようにノードをセットするかを見てきました。
 `nodePlacement` 内の `nodeSelector` は、あるノードのセットに Pod を引き寄せます。
しかし、反対に、Pod をなるノードから遠ざけたい場合は、どうすればいいでしょう？

Taint された(汚された)ノード上でPodが動作しないようにする事ができます。

これは、例えば、以下のようなユースケースで役に立つでしょう。：

* クラスタ内のノード(またはノードのグループ)は特別な目的のために予約されている。 
* 特定のタスクに特化したハードウェア(GPUのような)を持つノードがある。
* 特定のノードにだけ、その上で実行されているソフトウェアのライセンスを持っている。
* コンプライアンス上の理由から、ノードが異なるネットワークゾーンに存在する。
* 不具合のあるノードのトラブルシューティングを行いたい。

この演習では、Taint と Toleration を使用してワークロードを制御する方法を試して見ます。

---

### 背景

Taint と Toleration は、協調して動作し、ワークロードが他のノードにスケジュールされないようにします。
ノードが Taint になると、そのノードは Taint を許容しないワークロードを受け入れるべきではありません。
ワークロードに適用された Toleration は、対応する Pod を、マッチする Taint をもったノードにスケジュールする事を可能にします。（ただし、必要ではありません）
 
[NOTE]
====
ワークロードが常に特定のノードに配置されるようにするためには、`nodeSelector` を Taint と Toleration と一緒に使用する必要があります。
====

#### Examine node labels
ノードを調べるには、`kubeadmin` で実行していることを確認してください。

[.console-input]
[source,sh]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

インフラノードとストレージノード以外の、ワーカーノードをリストします。

[.console-input]
[source,sh]
----
oc get nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage'
----

どの演習をやったかにもよりますが、ワーカーラベルセットを持ったノードが3つ以上ある場合があります。

では、これらのワーカーノードに、何か Taint が設定されてないか見てみましょう。

[.console-input]
[source,sh]
----
oc describe nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage' | grep Taint
----

これらのワーカーノードに Taint は設定されてないはずです。

#### Deploying test application

この演習では、テスト用のアプリをデプロイします。

このアプリをデプロイする前に、この演習の期間中はノードにラベルを付ける必要があります。
アプリケーションは `appnode=welome-php` というラベルのついたノードにデプロイします。

[.console-input]
[source,sh]
----
oc get nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage' -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | xargs -I{} oc label node {} appnode=welcome-php
----

ノードにラベルを付けるには、ノード名をkey=valueのペアで渡します。例：oc label node worker.example.com appnode=welcome-php

ノードの名前をメモしながら、ノードがラベル付けされていることを確認します。

[.console-input]
[source,sh]
----
oc get nodes -l appnode=welcome-php
----

ホームディレクトリで提供されているYAMLマニフェストを使ってアプリケーションをデプロイすることができます。

[.console-input]
[source,sh]
----
oc create -f ~/support/welcome-php.yaml
----

以下のオブジェクトが作成されます。

* Namespace `tt-lab` 
* サンプルのphpアプリを実行している `welcome-php` というDeployment
* ポート `8080` で Listen する `welcome-php` というService
* `welcome-php` という名前のRoute


ここから `tt-lab` プロジェクトで作業しますので、切り替えます。

[.console-input]
[source,sh]
----
oc project tt-lab
----

ここで、Podをノードの数と同じにスケールさせます。
デフォルトのスケジューラは、アプリを均等に分散させようとします。
また、ロールアウトが完了するのを待ちます。

[.console-input]
[source,sh]
----
NODE_NUMBER=$(oc get nodes --no-headers -l appnode=welcome-php | wc -l) 
oc scale deploy welcome-php --replicas=${NODE_NUMBER}
oc rollout status deploy welcome-php
----

アプリケーションがロールアウトされたら、すべてのノードでリバランスされるように Pod を削除してみましょう。

[.console-input]
[source,sh]
----
oc delete pods --all
oc rollout status deploy welcome-php
----

Pod がworkerに均等に広がっていることを確認してください。各ノードに1つの Pod があるはずです。

[.console-input]
[source,sh]
----
clear
oc get pods -o=custom-columns=NAME:.metadata.name,NODE:.spec.nodeName
oc get nodes -l appnode=welcome-php
----

[NOTE]
====
Pod が均等に広がるようにするには、`oc delete pods --all` を何度か実行する必要があるかもしれません。
====

#### ノードを Taint する

これからノードを Taint して、ワークロードを拒否するようにします。
最初に、それぞれの Taint が何をするのかを説明します。
設定できる基本的な Taint は3つあります。

* `key=value:NoSchedule`
* `key=value:NoExecute`
* `key=value:PreferNoSchedule`

この場合の `key` は、253文字以内の任意の文字列です。
キーは文字か数字で始めなければならず、文字、数字、ハイフン、ドット、アンダースコアを含むことができます。

ここでの `value` は任意の文字列であり、63文字以内です。
値は文字か数字で始めなければならず、文字、数字、ハイフン、ドット、アンダースコアを含むことができます。


以下の 3 つの効果が現れます。: 

* `NoSchedule` - taint にマッチしない新しいPodは、そのノードにスケジュールされません。ノード上の既存のPodはそのまま残ります。
* `NoExecute` -  taint にマッチしない新しいPodは、そのノードにスケジューリングすることはできません。一致しないノード上の既存のPodは削除されます。
* `PreferNoSchedule` - taint にマッチしない新しいPodがそのノードにスケジューリングされることがありますが、スケジューラはそれを回避しようとします。ノード上の既存のPodは残ります。

もう一つのコンポーネントとして `operator` があります。 `operator` については「Toleration」のセクションで詳しく説明します。



この演習では、インフラ・ノードでもストレージ・ノードではない最初のノードを `welcome-php=run:NoSchedule` で Taint します。 
これにより、すべての新しいPod(適切な Toleration を持たないものは)は、このノードでスケジューリングされないようになります。

構文は　oc adm taint node ${nodename} key=value:Effect　です。

[.console-input]
[source,sh]
----
TTNODE=$(oc get nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage' -o jsonpath='{range .items[0]}{.metadata.name}')
oc adm taint node ${TTNODE} welcome-php=run:NoSchedule
----

デプロイしたノードを調べて、そのうちの1つのノードに Taint が適用されていることを確認します。

[.console-input]
[source,sh]
----
oc describe nodes -l appnode=welcome-php | grep Taint
----

`NoSchedule` を使用しているので、Podはまだそこにあるはずです。
`NoSchedule` はノード上での新しいPodの生成を停止するだけであることを覚えておいてください（コマンドは `1` を返すはずです）。

[.console-input]
[source,sh]
----
oc get pods -o wide | grep -c ${TTNODE}
----

Pod を削除して `replicaSet` が再配置するのを待ちましょう。

[.console-input]
[source,sh]
----
oc delete pods --all
oc rollout status deploy welcome-php
----

このデプロイメントには Toleration がないので、スケジューラは、Taint されたノードを除いたすべてのノードに Pod をデプロイします。
このコマンドは `0` を返すはずです。

[.console-input]
[source,sh]
----
oc get pods -o wide | grep -c ${TTNODE}
----

Pod が実行されている場所を調べる。

[.console-input]
[source,sh]
----
clear
oc get pods -o=custom-columns=NAME:.metadata.name,NODE:.spec.nodeName
oc get nodes -l appnode=welcome-php
----

#### Toleration

`toleration` は、スケジューリング中にノードの Taint を "許容 "する(または "無視 "する) Pod の方法です。
`toleration` は `podSpec` で適用され、以下の形式になります。

[source,yaml]
----
tolerations:
- key: "welcome-php"
  operator: "Equal"
  value: "run"
  effect: "NoSchedule"
----

もし Toleration が "マッチ " した場合、スケジューラはこのノードにワークロードをスケジュールします(必要に応じて...保証ではないことを覚えておいてください)。
`key` , `value` , `effect` にマッチしなければならないことに注意してください。
オペレータと呼ばれるものもあります。

`operator` には `Equal` か `Exists` を設定することができます。　

* `Equal` - パラメータ `key`, `value`, `effect` がマッチしなければいけません。これは何も指定しない場合のデフォルトの設定です。
* `Exists` - パラメータ `key` と `effect` がマッチしなければなりません。全てにマッチさせるには、値のパラメータは空白のままにしておく必要があります。

Deployment の `spec.template.spec` セクションでこの Toleration を適用します。

[.console-input]
[source,sh]
----
oc patch deployment welcome-php --patch '{"spec":{"template":{"spec":{"tolerations":[{"key":"welcome-php","operator":"Equal","value":"run","effect":"NoSchedule"}]}}}}'
----

パッチを当てると別の展開が始まるので、展開が終わるのを待つことにします。

[.console-input]
[source,sh]
----
oc rollout status deploy welcome-php
----

デプロイメントYAMLを見ることで、Toleration の設定を見ることができます。

[.console-input]
[source,sh]
----
oc get deploy welcome-php -o yaml
----

さて、Toleration を設定したので、Taint を持つノードで実行してみましょう (これは `1` を返すはずです)。

[.console-input]
[source,sh]
----
oc get pods -o wide | grep -c ${TTNODE}
----

すべてのPodをリストアップすると、それらが均等に広がっているはずです

[.console-input]
[source,sh]
----
clear
oc get pods -o=custom-columns=NAME:.metadata.name,NODE:.spec.nodeName
oc get nodes -l appnode=welcome-php
----

Taint と Toleration について、もっと良く知るには、https://docs.openshift.com/container-platform/4.2/nodes/scheduling/nodes-scheduler-taints-tolerations.html[Official Documentation] を読んでみて下さい。

#### クリーンアップ

次の演習では `kubeadmin` でログインしてください。

[.console-input]
[source,sh]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

他の演習も Taint の影響を受ける可能性があるので、やったことを元に戻しておきましょう。

[.console-input]
[source,sh]
----
oc delete project tt-lab
oc adm taint node ${TTNODE} welcome-php-
oc get nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage' -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | xargs -I{} oc label node {} appnode-
----

ノードの Taint が除去されていることを確認してください。

[.console-input]
[source,sh]
----
oc describe nodes -l 'node-role.kubernetes.io/worker,!node-role.kubernetes.io/infra,!cluster.ocs.openshift.io/openshift-storage' | grep Taint
----

また、作業していたノードにラベルが存在しないことを確認してください。
このコマンドはノードを返さないはずです。

[.console-input]
[source,sh]
----
oc get nodes -l appnode=welcome-php
----
